.TH "BaseElement" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseElement \- 
.PP
décorateur de la classe \fBElement\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseElement\&.h>\fP
.PP
Inherits \fBElement\fP\&.
.PP
Inherited by \fBPointBonusElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseElement\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fBBaseElement\fP (\fBElement\fP el)"
.br
.RI "\fIsurchage du constructeur \fP"
.ti -1c
.RI "virtual \fB~BaseElement\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.RI "\fIaccesseur de l'attribut value \fP"
.ti -1c
.RI "int \fBgetMoney\fP ()"
.br
.RI "\fIaccesseur de l'attribut money \fP"
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.RI "\fIaccesseur de l'attribut type \fP"
.ti -1c
.RI "void \fBsetType\fP (int type)"
.br
.RI "\fIsetteur de l'attribut value \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP \fBel_\fP"
.br
.RI "\fIl'attribut de type \fBElement\fP \fP"
.ti -1c
.RI "int \fBbonusValue_\fP"
.br
.RI "\fIl'attribut valeur du bonus de type entier \fP"
.ti -1c
.RI "int \fBbonusMoney_\fP"
.br
.RI "\fIl'attribut bonus \fP"
.in -1c
.SH "Detailed Description"
.PP 
décorateur de la classe \fBElement\fP 

La classe ajout d'un bonus en fonction d'un pourcentage de chance 
.PP
Definition at line 27 of file BaseElement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBaseElement::BaseElement\fP ()"
.PP
Constructeur\&. Constructeur de la classe \fBBaseElement\fP 
.PP
Definition at line 5 of file BaseElement\&.cpp\&.
.SS "\fBBaseElement::BaseElement\fP (\fBElement\fPel)"
.PP
surchage du constructeur surcharge du constructeur de la classe \fBBaseElement\fP
.PP
\fBParameters:\fP
.RS 4
\fI\fBElement\fP\fP : l'élément à décoré 
.RE
.PP

.PP
Definition at line 13 of file BaseElement\&.cpp\&.
.SS "\fBBaseElement::~BaseElement\fP ()\fC [virtual]\fP"
.PP
Destructeur\&. destructeur de la classe \fBBaseElement\fP 
.PP
Definition at line 20 of file BaseElement\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBBaseElement::getMoney\fP ()"
.PP
accesseur de l'attribut money Methode qui retourne la valeur de l'attribut money 
.PP
\fBReturns:\fP
.RS 4
entier ; 
.RE
.PP

.PP
Reimplemented from \fBElement\fP\&.
.PP
Reimplemented in \fBPointBonusElement\fP\&.
.PP
Definition at line 40 of file BaseElement\&.cpp\&.
.SS "int \fBBaseElement::getType\fP ()"
.PP
accesseur de l'attribut type Methode qui retourne la valeur de l'attribut type 
.PP
\fBReturns:\fP
.RS 4
entier ; 
.RE
.PP

.PP
Reimplemented from \fBElement\fP\&.
.PP
Definition at line 25 of file BaseElement\&.cpp\&.
.SS "int \fBBaseElement::getValue\fP ()"
.PP
accesseur de l'attribut value Methode qui retourne la valeur de l'attribut value 
.PP
\fBReturns:\fP
.RS 4
entier ; 
.RE
.PP

.PP
Reimplemented from \fBElement\fP\&.
.PP
Reimplemented in \fBPointBonusElement\fP\&.
.PP
Definition at line 35 of file BaseElement\&.cpp\&.
.SS "void \fBBaseElement::setType\fP (inttype)"
.PP
setteur de l'attribut value Methode qui retourne la valeur de l'attribut value 
.PP
\fBReturns:\fP
.RS 4
entier ; 
.RE
.PP

.PP
Reimplemented from \fBElement\fP\&.
.PP
Definition at line 30 of file BaseElement\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBBaseElement::bonusMoney_\fP\fC [protected]\fP"
.PP
l'attribut bonus 
.PP
Definition at line 105 of file BaseElement\&.h\&.
.SS "int \fBBaseElement::bonusValue_\fP\fC [protected]\fP"
.PP
l'attribut valeur du bonus de type entier 
.PP
Definition at line 101 of file BaseElement\&.h\&.
.SS "\fBElement\fP \fBBaseElement::el_\fP\fC [protected]\fP"
.PP
l'attribut de type \fBElement\fP 
.PP
Definition at line 97 of file BaseElement\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
