.TH "src/Button.cpp" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Button.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Button\&.h'\fP
.br
\fC#include <SDL/SDL\&.h>\fP
.br
\fC#include <SDL/SDL_image\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
