.TH "include/Define.h" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Define.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL/SDL\&.h>\fP
.br
\fC#include <SDL/SDL_ttf\&.h>\fP
.br
\fC#include <SDL/SDL_gfxPrimitives\&.h>\fP
.br
\fC#include <SDL_rotozoom\&.h>\fP
.br
\fC#include <SDL/SDL_framerate\&.h>\fP
.br
\fC#include <SDL/SDL_image\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'BaseElement\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector
.br
< std::vector< \fBBaseElement\fP > > \fBMatrix2DElement\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< std::array< int, 2 > > \fBVectorArray2I\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const bool \fBDEBUG\fP = true"
.br
.ti -1c
.RI "const int \fBFPS\fP = 30"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<std::vector<\fBBaseElement\fP> > \fBMatrix2DElement\fP"
.PP
Definition at line 16 of file Define\&.h\&.
.SS "typedef std::vector<std::array<int, 2> > \fBVectorArray2I\fP"
.PP
Definition at line 17 of file Define\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const bool \fBDEBUG\fP = true"
.PP
Definition at line 19 of file Define\&.h\&.
.SS "const int \fBFPS\fP = 30"
.PP
Definition at line 20 of file Define\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
