.TH "include/Element.h" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Element.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.RI "\fILa classe de gestion des éléments\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBNEUTRAL_ELEMENT\fP = 0"
.br
.ti -1c
.RI "const int \fBVALUE_ELEMENT\fP = 3"
.br
.ti -1c
.RI "const int \fBMONEY_ELEMENT\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int \fBMONEY_ELEMENT\fP = 0"
.PP
Definition at line 18 of file Element\&.h\&.
.SS "const int \fBNEUTRAL_ELEMENT\fP = 0"
.PP
Definition at line 16 of file Element\&.h\&.
.SS "const int \fBVALUE_ELEMENT\fP = 3"
.PP
Definition at line 17 of file Element\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
