.TH "Element" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Element \- 
.PP
La classe de gestion des éléments\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Element\&.h>\fP
.PP
Inherited by \fBBaseElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fBElement\fP (int type)"
.br
.RI "\fISurcharge du constructeur\&. \fP"
.ti -1c
.RI "\fBElement\fP (bool random, int n_el)"
.br
.RI "\fISurcharge du constructeur\&. \fP"
.ti -1c
.RI "\fB~Element\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.RI "\fIaccesseur de l'attribut value \fP"
.ti -1c
.RI "int \fBgetMoney\fP ()"
.br
.RI "\fIaccesseur de l'attribut Money \fP"
.ti -1c
.RI "int \fBgetType\fP ()"
.br
.RI "\fIaccesseur de l'attribut type \fP"
.ti -1c
.RI "void \fBsetType\fP (int type)"
.br
.RI "\fIsetteur de l'attribut type \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBtype_\fP"
.br
.RI "\fIattribut type de l'élément \fP"
.ti -1c
.RI "int \fBvalue_\fP"
.br
.RI "\fIattribut value; \fP"
.ti -1c
.RI "int \fBmoney_\fP"
.br
.RI "\fIattribut money; \fP"
.in -1c
.SH "Detailed Description"
.PP 
La classe de gestion des éléments\&. 
.PP
Definition at line 26 of file Element\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBElement::Element\fP ()"
.PP
Constructeur\&. Constructeur de la classe element 
.PP
Definition at line 4 of file Element\&.cpp\&.
.SS "\fBElement::Element\fP (inttype)"
.PP
Surcharge du constructeur\&. surcharge du constructeur de la classe \fBElement\fP
.PP
\fBParameters:\fP
.RS 4
\fIint\fP type d'élément 
.RE
.PP

.PP
Definition at line 11 of file Element\&.cpp\&.
.SS "\fBElement::Element\fP (boolrandom, intn_el)"
.PP
Surcharge du constructeur\&. surcharge du constructeur de la classe \fBElement\fP
.PP
\fBParameters:\fP
.RS 4
\fIbooléen\fP random pour la gestion de l'aléatoire 
.br
\fIentier\fP nombre d'élément 
.RE
.PP

.PP
Definition at line 18 of file Element\&.cpp\&.
.SS "\fBElement::~Element\fP ()"
.PP
Destructeur\&. destructeur de la classe \fBElement\fP 
.PP
Definition at line 31 of file Element\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBElement::getMoney\fP ()"
.PP
accesseur de l'attribut Money Methode qui retourne la money de l'élément 
.PP
\fBReturns:\fP
.RS 4
entier ; 
.RE
.PP

.PP
Reimplemented in \fBBaseElement\fP, and \fBPointBonusElement\fP\&.
.PP
Definition at line 33 of file Element\&.cpp\&.
.SS "int \fBElement::getType\fP ()"
.PP
accesseur de l'attribut type Methode qui retourne le type de l'élément 
.PP
\fBReturns:\fP
.RS 4
entier le type de l'élément ; 
.RE
.PP

.PP
Reimplemented in \fBBaseElement\fP\&.
.PP
Definition at line 43 of file Element\&.cpp\&.
.SS "int \fBElement::getValue\fP ()"
.PP
accesseur de l'attribut value Methode qui retourne la valeur de l'élément 
.PP
\fBReturns:\fP
.RS 4
entier, la valeur de l'élément 
.RE
.PP

.PP
Reimplemented in \fBBaseElement\fP, and \fBPointBonusElement\fP\&.
.PP
Definition at line 38 of file Element\&.cpp\&.
.SS "void \fBElement::setType\fP (inttype)"
.PP
setteur de l'attribut type Methode qui affecte un nouveau type à l'élément 
.PP
\fBParameters:\fP
.RS 4
\fIentier\fP le nouveau type ; 
.RE
.PP

.PP
Reimplemented in \fBBaseElement\fP\&.
.PP
Definition at line 48 of file Element\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBElement::money_\fP\fC [protected]\fP"
.PP
attribut money; 
.PP
Definition at line 120 of file Element\&.h\&.
.SS "int \fBElement::type_\fP\fC [protected]\fP"
.PP
attribut type de l'élément 
.PP
Definition at line 110 of file Element\&.h\&.
.SS "int \fBElement::value_\fP\fC [protected]\fP"
.PP
attribut value; 
.PP
Definition at line 115 of file Element\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
