.TH "include/GameScreen.h" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/GameScreen.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Screen\&.h'\fP
.br
\fC#include 'ElementUI\&.h'\fP
.br
\fC#include 'Button\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameScreen\fP"
.br
.RI "\fILa classe \fBGameScreen\fP, gestion de l'écran de jeux implémente l'interface \fBScreen\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
