.TH "GridMode" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridMode \- 
.PP
Interface \fBGridMode\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GridMode\&.h>\fP
.PP
Inherited by \fBGridModeHard\fP, and \fBGridModeNormal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~GridMode\fP ()"
.br
.RI "\fI'Constructeur' \fP"
.ti -1c
.RI "virtual bool \fBpurge\fP (\fBGrid\fP *grid)=0"
.br
.RI "\fImethode purge \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBGridMode\fP\&. 
.PP
Definition at line 26 of file GridMode\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual \fBGridMode::~GridMode\fP ()\fC [inline, virtual]\fP"
.PP
'Constructeur' 'Constructeur' de la classe \fBGridMode\fP 
.PP
Definition at line 35 of file GridMode\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool \fBGridMode::purge\fP (\fBGrid\fP *grid)\fC [pure virtual]\fP"
.PP
methode purge surchage de la methode purge de la classe \fBGrid\fP 
.PP
\fBParameters:\fP
.RS 4
\fI\fBGrid\fP,pointeur\fP sur la grille 
.RE
.PP
\fBReturns:\fP
.RS 4
booléen 
.RE
.PP

.PP
Implemented in \fBGridModeHard\fP, and \fBGridModeNormal\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
