.TH "GridModeHard" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridModeHard \- 
.PP
La classe \fBGridModeHard\fP, implémente la \fBGridMode\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GridModeHard\&.h>\fP
.PP
Inherits \fBGridMode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridModeHard\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "virtual \fB~GridModeHard\fP ()"
.br
.RI "\fIdestructeur \fP"
.ti -1c
.RI "bool \fBpurge\fP (\fBGrid\fP *grid)"
.br
.RI "\fImethode purge \fP"
.ti -1c
.RI "\fBVectorArray2I\fP \fBcheck_row\fP (\fBGrid\fP *grid, int i_row)"
.br
.RI "\fImethode check_row \fP"
.ti -1c
.RI "\fBVectorArray2I\fP \fBcheck_col\fP (\fBGrid\fP *grid, int i_col)"
.br
.RI "\fImethode check_col \fP"
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBGridModeHard\fP, implémente la \fBGridMode\fP\&. 
.PP
Definition at line 23 of file GridModeHard\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGridModeHard::GridModeHard\fP ()"
.PP
Constructeur\&. Constructeur de la classe \fBGridModeHard\fP 
.PP
Definition at line 5 of file GridModeHard\&.cpp\&.
.SS "\fBGridModeHard::~GridModeHard\fP ()\fC [virtual]\fP"
.PP
destructeur destructeur de la classe \fBGridModeHard\fP 
.PP
Definition at line 9 of file GridModeHard\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBVectorArray2I\fP \fBGridModeHard::check_col\fP (\fBGrid\fP *grid, inti_col)"
.PP
methode check_col méthode qui vérifie la colonne i_col de la grille, retourne la liste des éléments à retirer 
.PP
\fBParameters:\fP
.RS 4
\fI\fBGrid\fP,la\fP grille sur laquelle vérifier la ligne 
.br
\fIEntier,la\fP colonne à vérifier 
.RE
.PP
\fBReturns:\fP
.RS 4
VectorArray2I, la liste des éléments à retirer 
.RE
.PP

.PP
Definition at line 104 of file GridModeHard\&.cpp\&.
.SS "\fBVectorArray2I\fP \fBGridModeHard::check_row\fP (\fBGrid\fP *grid, inti_row)"
.PP
methode check_row méthode qui vérifie la ligne i_row de la grille, retourne la liste des éléments à retirer 
.PP
\fBParameters:\fP
.RS 4
\fI\fBGrid\fP,la\fP grille sur laquelle vérifier la ligne 
.br
\fIEntier,la\fP ligne à vérifier 
.RE
.PP
\fBReturns:\fP
.RS 4
VectorArray2I, la liste des éléments à retirer 
.RE
.PP

.PP
Definition at line 49 of file GridModeHard\&.cpp\&.
.SS "bool \fBGridModeHard::purge\fP (\fBGrid\fP *grid)\fC [virtual]\fP"
.PP
methode purge 
.PP
Implements \fBGridMode\fP\&.
.PP
Definition at line 14 of file GridModeHard\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
