.TH "include/GridMode.h" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/GridMode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'Define\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGridMode\fP"
.br
.RI "\fIInterface \fBGridMode\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
