.TH "include/Grid.h" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Grid.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Define\&.h'\fP
.br
\fC#include 'BaseElement\&.h'\fP
.br
\fC#include 'PointBonusElement\&.h'\fP
.br
\fC#include 'GridMode\&.h'\fP
.br
\fC#include 'GridModeNormal\&.h'\fP
.br
\fC#include 'GridModeHard\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGrid\fP"
.br
.RI "\fILa classe \fBGrid\fP, classe de gestion de la grille de jeux\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
