.TH "main.cpp" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'include/Define\&.h'\fP
.br
\fC#include 'include/Engine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (void)"
.PP
Definition at line 6 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
