.TH "Player" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- 
.PP
La classe \fBPlayer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP ()"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "\fBPlayer\fP (string name, int money, vector< int > highscore)"
.br
.RI "\fISurchage du Constructeur\&. \fP"
.ti -1c
.RI "virtual \fB~Player\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "int \fBgetMoney\fP ()"
.br
.ti -1c
.RI "vector< int > \fBgetHighscore\fP ()"
.br
.ti -1c
.RI "void \fBsetMoney\fP (int money)"
.br
.ti -1c
.RI "void \fBsetHighscore\fP (vector< int > highscore)"
.br
.ti -1c
.RI "void \fBsetName\fP (string name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBPlayer\fP\&. 
.PP
Definition at line 24 of file Player\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPlayer::Player\fP ()"
.PP
Constructeur\&. Constructeur de la classe \fBPlayer\fP 
.PP
Definition at line 3 of file Player\&.cpp\&.
.SS "\fBPlayer::Player\fP (stringname, intmoney, vector< int >highscore)"
.PP
Surchage du Constructeur\&. Surchage du Constructeur de la classe \fBPlayer\fP 
.PP
\fBParameters:\fP
.RS 4
\fIstring,le\fP nom du joueur 
.br
\fIEntier,money\fP l'argent du joueur 
.br
\fIvector<int>,liste\fP des score du joueur 
.RE
.PP

.PP
Definition at line 9 of file Player\&.cpp\&.
.SS "\fBPlayer::~Player\fP ()\fC [virtual]\fP"
.PP
Destructeur\&. Destructeur de la classe \fBPlayer\fP 
.PP
Definition at line 16 of file Player\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< int > \fBPlayer::getHighscore\fP ()"
.PP
Definition at line 34 of file Player\&.cpp\&.
.SS "int \fBPlayer::getMoney\fP ()"
.PP
Definition at line 29 of file Player\&.cpp\&.
.SS "string \fBPlayer::getName\fP ()"
.PP
Definition at line 24 of file Player\&.cpp\&.
.SS "void \fBPlayer::setHighscore\fP (vector< int >highscore)"
.PP
Definition at line 47 of file Player\&.cpp\&.
.SS "void \fBPlayer::setMoney\fP (intmoney)"
.PP
Definition at line 42 of file Player\&.cpp\&.
.SS "void \fBPlayer::setName\fP (stringname)"
.PP
Definition at line 51 of file Player\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
