.TH "PointBonusElement" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointBonusElement \- 
.PP
La classe \fBPointBonusElement\fP, hérite de \fBBaseElement\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PointBonusElement\&.h>\fP
.PP
Inherits \fBBaseElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPointBonusElement\fP (\fBElement\fP el)"
.br
.RI "\fIConstructeur\&. \fP"
.ti -1c
.RI "virtual \fB~PointBonusElement\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.RI "\fIAccesseur\&. \fP"
.ti -1c
.RI "int \fBgetMoney\fP ()"
.br
.RI "\fIAccesseur\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
La classe \fBPointBonusElement\fP, hérite de \fBBaseElement\fP\&. 
.PP
Definition at line 21 of file PointBonusElement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPointBonusElement::PointBonusElement\fP (\fBElement\fPel)"
.PP
Constructeur\&. Constructeur de la classe \fBPointBonusElement\fP 
.PP
\fBParameters:\fP
.RS 4
\fI\fBElement\fP,l'élément\fP à décoré 
.RE
.PP

.PP
Definition at line 3 of file PointBonusElement\&.cpp\&.
.SS "\fBPointBonusElement::~PointBonusElement\fP ()\fC [virtual]\fP"
.PP
Destructeur\&. Destructeur de la classe \fBPointBonusElement\fP 
.PP
Definition at line 9 of file PointBonusElement\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBPointBonusElement::getMoney\fP ()"
.PP
Accesseur\&. accesseur de l'attribut money de l'élément 
.PP
Reimplemented from \fBBaseElement\fP\&.
.PP
Definition at line 20 of file PointBonusElement\&.cpp\&.
.SS "int \fBPointBonusElement::getValue\fP ()"
.PP
Accesseur\&. accesseur de l'attribut valeur de l'élément 
.PP
Reimplemented from \fBBaseElement\fP\&.
.PP
Definition at line 14 of file PointBonusElement\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
