.TH "Screen" 3 "Mon Nov 25 2013" "Version 1.0" "Swird-Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen \- 
.PP
Interface \fBScreen\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Screen\&.h>\fP
.PP
Inherited by \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Screen\fP ()"
.br
.RI "\fIDestructeur\&. \fP"
.ti -1c
.RI "virtual void \fBshow\fP (SDL_Surface *screen)=0"
.br
.RI "\fImethode show \fP"
.ti -1c
.RI "virtual void \fBrender\fP (SDL_Surface *screen)=0"
.br
.RI "\fImethode render \fP"
.ti -1c
.RI "virtual void \fBresize\fP (SDL_Surface *screen)=0"
.br
.RI "\fImethode resize \fP"
.ti -1c
.RI "virtual void \fBhide\fP (SDL_Surface *screen)=0"
.br
.RI "\fImethode hide \fP"
.ti -1c
.RI "virtual void \fBevent\fP (SDL_Event *\fBevent\fP, bool *loop)=0"
.br
.RI "\fImethode event \fP"
.ti -1c
.RI "virtual void \fBmouseClick\fP (int x, int y)=0"
.br
.RI "\fImethode mouseClick \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBScreen\fP\&. 
.PP
Definition at line 23 of file Screen\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual \fBScreen::~Screen\fP ()\fC [inline, virtual]\fP"
.PP
Destructeur\&. Destructeur de la classe \fBScreen\fP 
.PP
Definition at line 32 of file Screen\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void \fBScreen::event\fP (SDL_Event *event, bool *loop)\fC [pure virtual]\fP"
.PP
methode event methode qui gère l'ensemble des événements liés à l'écran
.PP
\fBParameters:\fP
.RS 4
\fISDL_Event,l'évenement\fP sdl 
.br
\fIbooléen,la\fP boucle 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "virtual void \fBScreen::hide\fP (SDL_Surface *screen)\fC [pure virtual]\fP"
.PP
methode hide methode qui 'cache' l'écran
.PP
\fBParameters:\fP
.RS 4
\fISDl_Surface\fP 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "virtual void \fBScreen::mouseClick\fP (intx, inty)\fC [pure virtual]\fP"
.PP
methode mouseClick methode qui permet la gestion du clique sur l'écran
.PP
\fBParameters:\fP
.RS 4
\fIentier,l'abscisse\fP 
.br
\fIentier,l'ordonnée\fP 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "virtual void \fBScreen::render\fP (SDL_Surface *screen)\fC [pure virtual]\fP"
.PP
methode render methode qui gère l'affichage de l'écran
.PP
\fBParameters:\fP
.RS 4
\fISDl_Surface,l'écran\fP 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "virtual void \fBScreen::resize\fP (SDL_Surface *screen)\fC [pure virtual]\fP"
.PP
methode resize methode qui permet de redimensionner la taille de la fenêtre
.PP
\fBParameters:\fP
.RS 4
\fISDl_Surface,l'écran\fP a redimensionner 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.
.SS "virtual void \fBScreen::show\fP (SDL_Surface *screen)\fC [pure virtual]\fP"
.PP
methode show methode permettant d'afficher l'écran ( appeler une fois )
.PP
\fBParameters:\fP
.RS 4
\fISDl_Surface,l'écran\fP 
.RE
.PP

.PP
Implemented in \fBGameScreen\fP, and \fBMenuScreen\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Swird-Project from the source code\&.
